"""Fourth Migration

Revision ID: a02a0161f323
Revises: 70e722d36ace
Create Date: 2020-06-07 07:22:25.903028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a02a0161f323'
down_revision = '70e722d36ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitches_description'), 'pitches', ['description'], unique=False)
    op.drop_index('ix_soundbyts_category', table_name='soundbyts')
    op.drop_table('soundbyts')
    op.add_column('comments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('comments_soundbyt_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_users_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_column('comments', 'users_id')
    op.drop_column('comments', 'soundbyt_id')
    op.drop_column('comments', 'comment')
    op.add_column('downvotes', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('downvotes', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.drop_constraint('downvotes_soundbyt_id_fkey', 'downvotes', type_='foreignkey')
    op.create_foreign_key(None, 'downvotes', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('downvotes', 'soundbyt_id')
    op.add_column('upvotes', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.add_column('upvotes', sa.Column('upvote', sa.Integer(), nullable=True))
    op.drop_constraint('upvotes_soundbyt_id_fkey', 'upvotes', type_='foreignkey')
    op.create_foreign_key(None, 'upvotes', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('upvotes', 'soundbyt_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('soundbyt_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.create_foreign_key('upvotes_soundbyt_id_fkey', 'upvotes', 'soundbyts', ['soundbyt_id'], ['id'])
    op.drop_column('upvotes', 'upvote')
    op.drop_column('upvotes', 'pitch_id')
    op.add_column('downvotes', sa.Column('soundbyt_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.create_foreign_key('downvotes_soundbyt_id_fkey', 'downvotes', 'soundbyts', ['soundbyt_id'], ['id'])
    op.drop_column('downvotes', 'pitch_id')
    op.drop_column('downvotes', 'downvote')
    op.add_column('comments', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('soundbyt_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_users_id_fkey', 'comments', 'users', ['users_id'], ['id'])
    op.create_foreign_key('comments_soundbyt_id_fkey', 'comments', 'soundbyts', ['soundbyt_id'], ['id'])
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'pitch_id')
    op.drop_column('comments', 'description')
    op.create_table('soundbyts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('soundbyt', sa.VARCHAR(length=700), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='soundbyts_users_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='soundbyts_pkey')
    )
    op.create_index('ix_soundbyts_category', 'soundbyts', ['category'], unique=False)
    op.drop_index(op.f('ix_pitches_description'), table_name='pitches')
    op.drop_table('pitches')
    # ### end Alembic commands ###
